# Generated by Django 5.2.7 on 2025-12-05 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('refrain', models.TextField(blank=True, help_text="Refrain chanté par l'assemblée")),
                ('versets', models.TextField(blank=True)),
                ('partition_pdf', models.FileField(blank=True, null=True, upload_to='partitions/pdf/', verbose_name='Partition PDF')),
                ('partition_mxl', models.FileField(blank=True, null=True, upload_to='partitions/mxl/', verbose_name='Partition MXL')),
            ],
            options={
                'verbose_name': 'Chant',
                'verbose_name_plural': 'Chants',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Compositeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Compositeur',
                'verbose_name_plural': 'Compositeurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Cantique',
            fields=[
                ('chant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psaumes.chant')),
                ('reference_biblique', models.CharField(db_index=True, help_text='Référence biblique (ex: Is 12,1-6, Ap 19,1-8)', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Cantique',
                'verbose_name_plural': 'Cantiques',
                'ordering': ['reference_biblique'],
            },
            bases=('psaumes.chant',),
        ),
        migrations.CreateModel(
            name='Psaume',
            fields=[
                ('chant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psaumes.chant')),
                ('numero', models.IntegerField(db_index=True, unique=True)),
            ],
            options={
                'verbose_name': 'Psaume',
                'verbose_name_plural': 'Psaumes',
                'ordering': ['numero'],
            },
            bases=('psaumes.chant',),
        ),
        migrations.AddField(
            model_name='chant',
            name='compositeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chants', to='psaumes.compositeur'),
        ),
        migrations.CreateModel(
            name='FichierAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_voix', models.CharField(choices=[('S', 'Soprano'), ('A', 'Alto'), ('T', 'Ténor'), ('B', 'Basse'), ('I', 'Instrumental'), ('M', 'Mix complet')], max_length=1)),
                ('fichier', models.FileField(upload_to='audios/')),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='psaumes.chant')),
            ],
            options={
                'verbose_name': 'Fichier audio',
                'verbose_name_plural': 'Fichiers audio',
                'unique_together': {('chant', 'type_voix')},
            },
        ),
        migrations.CreateModel(
            name='MomentLiturgique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.CharField(blank=True, choices=[('AVENT', "Temps de l'Avent"), ('NOEL', 'Temps de Noël'), ('ORDINAIRE', 'Temps Ordinaire'), ('CAREME', 'Temps de Carême'), ('SAINT', 'Semaine Sainte'), ('PASCAL', 'Temps Pascal')], help_text='Temps liturgique (vide si fête spéciale)', max_length=20)),
                ('semaine', models.PositiveSmallIntegerField(blank=True, help_text='Numéro de semaine (vide si fête spéciale)', null=True)),
                ('jour', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Dimanche'), (1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')], help_text='Jour (Dimanche ou Lundi-Samedi)', null=True)),
                ('parite', models.CharField(blank=True, choices=[('P', 'Année paire'), ('I', 'Année impaire')], help_text='Année paire/impaire - jours Lundi-Samedi uniquement', max_length=1)),
                ('annee', models.CharField(blank=True, choices=[('A', 'Année A'), ('B', 'Année B'), ('C', 'Année C')], help_text='Année A/B/C - Dimanche uniquement', max_length=1)),
                ('nom_fete', models.CharField(blank=True, help_text='Nom de la fête - FÊTE uniquement (ex: Nativité, Ascension...)', max_length=200)),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments_liturgiques', to='psaumes.chant')),
            ],
            options={
                'verbose_name': 'Moment liturgique',
                'verbose_name_plural': 'Moments liturgiques',
                'ordering': ['temps', 'semaine', 'jour'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('annee__isnull', False), models.Q(('annee', ''), _negated=True)), fields=('temps', 'semaine', 'annee'), name='unique_dimanche'), models.UniqueConstraint(condition=models.Q(('jour__isnull', False)), fields=('temps', 'semaine', 'jour', 'parite'), name='unique_semaine'), models.UniqueConstraint(condition=models.Q(('nom_fete', ''), _negated=True), fields=('nom_fete',), name='unique_fete')],
            },
        ),
    ]
