# Generated by Django 5.2.7 on 2025-12-12 15:43

import psaumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chant',
            name='partition_mxl',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.partition_mxl_path, verbose_name='Partition MXL'),
        ),
        migrations.AlterField(
            model_name='chant',
            name='partition_pdf',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.partition_pdf_path, verbose_name='Partition PDF'),
        ),
        migrations.AlterField(
            model_name='fichieraudio',
            name='fichier',
            field=models.FileField(upload_to=psaumes.models.partition_audio_path),
        ),
    ]
