# Generated by Django 5.2.7 on 2025-12-16 10:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0002_alter_chant_partition_mxl_alter_chant_partition_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chant',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='chant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chant_search_idx'),
        ),
    ]
