# Generated by Django 5.2.7 on 2025-12-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0003_chant_search_vector_chant_chant_search_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='momentliturgique',
            name='unique_dimanche',
        ),
        migrations.RemoveConstraint(
            model_name='momentliturgique',
            name='unique_semaine',
        ),
        migrations.AddConstraint(
            model_name='momentliturgique',
            constraint=models.UniqueConstraint(condition=models.Q(('jour', 0), ('annee__isnull', False), models.Q(('annee', ''), _negated=True)), fields=('temps', 'semaine', 'jour', 'annee'), name='unique_dimanche'),
        ),
        migrations.AddConstraint(
            model_name='momentliturgique',
            constraint=models.UniqueConstraint(condition=models.Q(('jour__gt', 0)), fields=('temps', 'semaine', 'jour', 'parite'), name='unique_semaine'),
        ),
    ]
