# Generated by Django 5.2.7 on 2025-12-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0004_remove_momentliturgique_unique_dimanche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psaume',
            name='numero',
            field=models.IntegerField(db_index=True),
        ),
    ]
