# Generated by Django 5.2.7 on 2025-12-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0005_remove_unique_constraint_on_numero'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='momentliturgique',
            name='unique_fete',
        ),
        migrations.AlterField(
            model_name='momentliturgique',
            name='nom_fete',
            field=models.CharField(blank=True, help_text="Nom de la fête - FÊTE uniquement (ex: Nativité, Ascension...). Pour les fêtes cycliques (Trinité...), ajouter aussi l'année A/B/C.", max_length=200),
        ),
        migrations.AddConstraint(
            model_name='momentliturgique',
            constraint=models.UniqueConstraint(condition=models.Q(('nom_fete', ''), _negated=True), fields=('nom_fete', 'annee'), name='unique_fete'),
        ),
    ]
