# Generated by Django 5.2.7 on 2025-12-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0006_remove_momentliturgique_unique_fete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichieraudio',
            name='type_voix',
            field=models.CharField(choices=[('S', 'Soprano'), ('A', 'Alto'), ('T', 'Ténor'), ('B', 'Basse'), ('I', 'Instrumental')], max_length=1),
        ),
    ]
