# Generated by Django 5.2.7 on 2025-12-19 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0007_alter_fichieraudio_type_voix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentliturgique',
            name='chant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moments_liturgiques', to='psaumes.chant'),
        ),
    ]
