# Generated by Django 5.2.9 on 2025-12-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0008_chant_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichieraudio',
            name='est_synthetique',
            field=models.BooleanField(default=False, help_text='Audio généré automatiquement à partir du fichier MXL'),
        ),
    ]
