# Generated by Django 5.2.9 on 2026-01-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0010_remove_unique_from_cantique_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='chant',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
