# Generated by Django 5.2.9 on 2026-01-04 00:09

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0011_add_slug_field'),
    ]

    operations = [
        UnaccentExtension(),
    ]
