# Generated by Django 5.2.9 on 2026-01-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0014_add_moment_liturgique_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantique',
            name='nom_complet_recherche',
            field=models.TextField(blank=True, db_index=True, help_text='Auto-généré pour recherche trigram'),
        ),
        migrations.AddField(
            model_name='momentliturgique',
            name='nom_complet_recherche',
            field=models.TextField(blank=True, db_index=True, help_text='Auto-généré pour recherche trigram'),
        ),
        migrations.AddField(
            model_name='psaume',
            name='nom_complet_recherche',
            field=models.TextField(blank=True, db_index=True, help_text='Auto-généré pour recherche trigram'),
        ),
    ]
