# Generated by Django 5.2.9 on 2026-01-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0015_add_nom_complet_recherche_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichieraudio',
            name='type_voix',
            field=models.CharField(choices=[('S', 'Soprano'), ('A', 'Alto'), ('T', 'Ténor'), ('B', 'Basse'), ('I', 'Instrumental'), ('M', 'Mix')], max_length=1),
        ),
    ]
