# Generated by Django 5.2.9 on 2026-01-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0016_add_mix_voix_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texte de la bannière')),
                ('active', models.BooleanField(default=False, verbose_name='Actif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bannière',
                'verbose_name_plural': 'Bannières',
            },
        ),
    ]
