# Generated by Django 5.2.9 on 2026-01-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0017_sitebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebanner',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
    ]
