# Generated by Django 5.2.11 on 2026-02-10 17:48

import psaumes.models.utils
from django.db import migrations, models


def move_audio_to_partition(apps, schema_editor):
    Partition = apps.get_model('psaumes', 'Partition')
    FichierAudio = apps.get_model('psaumes', 'FichierAudio')
    
    # Map voice types to fields
    field_map = {
        'S': 'audio_soprano',
        'A': 'audio_alto',
        'T': 'audio_tenor',
        'B': 'audio_basse',
        'I': 'audio_instrumental',
        'M': 'audio_mix',
    }
    
    for partition in Partition.objects.all():
        audios = FichierAudio.objects.filter(partition=partition)
        if audios.exists():
            any_synth = False
            for audio in audios:
                field_name = field_map.get(audio.type_voix)
                if field_name:
                    setattr(partition, field_name, audio.fichier.name)
                if audio.est_synthetique:
                    any_synth = True
            partition.mp3_synthetiques = any_synth
            partition.save()


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0019_manual_structural_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='audio_alto',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_alto_path, verbose_name='Audio Alto'),
        ),
        migrations.AddField(
            model_name='partition',
            name='audio_basse',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_basse_path, verbose_name='Audio Basse'),
        ),
        migrations.AddField(
            model_name='partition',
            name='audio_instrumental',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_instrumental_path, verbose_name='Audio Instrumental'),
        ),
        migrations.AddField(
            model_name='partition',
            name='audio_mix',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_mix_path, verbose_name='Audio Mix'),
        ),
        migrations.AddField(
            model_name='partition',
            name='audio_soprano',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_soprano_path, verbose_name='Audio Soprano'),
        ),
        migrations.AddField(
            model_name='partition',
            name='audio_tenor',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_tenor_path, verbose_name='Audio Ténor'),
        ),
        migrations.AddField(
            model_name='partition',
            name='mp3_synthetiques',
            field=models.BooleanField(default=False, help_text='MP3 générés automatiquement à partir du fichier MXL'),
        ),
        migrations.RunPython(move_audio_to_partition, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='FichierAudio',
        ),
    ]
