# Generated by Django 5.2.11 on 2026-02-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0020_merge_audio_to_partition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psaume',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='psaume',
            name='reference_biblique',
        ),
    ]
