# Generated by Django 5.2.9 on 2026-04-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0023_partition_audio_generation_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentliturgique',
            name='nom_fete',
            field=models.CharField(blank=True, help_text="Nom de la fête - FÊTE uniquement (ex: Nativité, Ascension, Sainte Trinité...). Pour les fêtes cycliques (Sainte Trinité...), ajouter aussi l'année A/B/C.", max_length=200),
        ),
    ]
