# Generated by Django 5.2.9 on 2026-04-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0024_alter_momentliturgique_nom_fete_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='text',
            field=models.TextField(help_text="Texte brut uniquement. Le HTML est échappé à l'affichage.", verbose_name='Texte de la bannière'),
        ),
    ]
