# Generated by Django 5.2.9 on 2026-04-17 09:10

import psaumes.models.utils
import psaumes.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0025_alter_sitebanner_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='audio_alto',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_alto_path, validators=[psaumes.models.validators.validate_mp3_upload], verbose_name='Audio Alto'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='audio_basse',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_basse_path, validators=[psaumes.models.validators.validate_mp3_upload], verbose_name='Audio Basse'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='audio_instrumental',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_instrumental_path, validators=[psaumes.models.validators.validate_mp3_upload], verbose_name='Audio Instrumental'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='audio_mix',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_mix_path, validators=[psaumes.models.validators.validate_mp3_upload], verbose_name='Audio Mix'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='audio_soprano',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_soprano_path, validators=[psaumes.models.validators.validate_mp3_upload], verbose_name='Audio Soprano'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='audio_tenor',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_tenor_path, validators=[psaumes.models.validators.validate_mp3_upload], verbose_name='Audio Ténor'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='partition_mxl',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_mxl_path, validators=[psaumes.models.validators.validate_mxl_upload], verbose_name='Partition MXL'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='partition_pdf',
            field=models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_pdf_path, validators=[psaumes.models.validators.validate_pdf_upload], verbose_name='Partition PDF'),
        ),
    ]
