# Generated by Django 5.2.9 on 2026-04-17 11:41

import django.db.models.deletion
import psaumes.models.utils
import psaumes.models.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0026_add_partition_file_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartitionAudioTempoVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_type', models.CharField(choices=[('S', 'Soprano'), ('A', 'Alto'), ('T', 'Ténor'), ('B', 'Basse'), ('I', 'Instrumental')], max_length=1)),
                ('tempo', models.DecimalField(choices=[(Decimal('0.50'), '0.5x'), (Decimal('1.00'), '1.0x'), (Decimal('1.50'), '1.5x')], db_index=True, decimal_places=2, max_digits=3)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=psaumes.models.utils.partition_audio_tempo_variant_path, validators=[psaumes.models.validators.validate_mp3_upload], verbose_name='Audio tempo Apple/Safari')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempo_variants', to='psaumes.partition')),
            ],
            options={
                'verbose_name': 'Variante audio tempo',
                'verbose_name_plural': 'Variantes audio tempo',
                'ordering': ['partition_id', 'tempo', 'voice_type'],
                'constraints': [models.UniqueConstraint(fields=('partition', 'voice_type', 'tempo'), name='unique_partition_voice_tempo_variant')],
            },
        ),
    ]
