# Generated by Django 5.2.9 on 2026-06-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0032_partition_omr_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='audio_channels',
            field=models.JSONField(blank=True, default=dict, help_text='Cache du nombre de canaux audio par champ (ex. {"audio_soprano": 1}). Invalide les requêtes R2 HEAD/GET.'),
        ),
        migrations.AddField(
            model_name='partitionaudiotempovariant',
            name='audio_channels',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cache du nombre de canaux audio du fichier. Invalide les requêtes R2 HEAD/GET lors de la détection mono.', null=True),
        ),
    ]
