# Generated by Django 5.2.11 on 2026-06-20 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0034_sequences_saint_sacrement_trinite'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='partie_messe',
            field=models.CharField(blank=True, choices=[('KYRIE', 'Kyrie'), ('GLORIA', 'Gloria'), ('SANCTUS', 'Sanctus'), ('AGNUS_DEI', 'Agnus Dei'), ('ALLELUIA', 'Alléluia'), ('ANAMNESE', 'Anamnèse')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Ordinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('compositeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordinaires', to='psaumes.compositeur')),
            ],
            options={
                'verbose_name': 'Ordinaire',
                'verbose_name_plural': 'Ordinaires',
                'ordering': ['titre'],
            },
        ),
        migrations.AddField(
            model_name='partition',
            name='ordinaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partitions_messe', to='psaumes.ordinaire'),
        ),
    ]
