# Generated by Django 5.2.9 on 2026-06-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psaumes', '0035_partition_partie_messe_ordinaire_partition_ordinaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='partie_messe',
            field=models.CharField(blank=True, choices=[('KYRIE', 'Kyrie'), ('GLORIA', 'Gloria'), ('SANCTUS', 'Sanctus'), ('AGNUS_DEI', 'Agnus Dei'), ('ALLELUIA', 'Alléluia'), ('ANAMNESE', 'Anamnèse'), ('PRIERE_UNIVERSELLE', 'Prière Universelle')], default='', max_length=20),
        ),
    ]
